name: Integration test application

on:
  pull_request:
    types: ["opened", "reopened", "edited"]
    branches:
      - master

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test
      - run: npm run generate --fail-on-error